# Generated by Django 5.1.15 on 2026-07-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='compromisedcredential',
            new_name='intel_compr_domain_2d1a18_idx',
            old_name='intel_compr_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='compromisedcredential',
            new_name='intel_compr_stealer_b2261b_idx',
            old_name='intel_compr_stealer_idx',
        ),
        migrations.RenameIndex(
            model_name='dataleak',
            new_name='intel_datal_leak_ty_3115dc_idx',
            old_name='intel_datal_leak_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='dataleak',
            new_name='intel_datal_affecte_532c19_idx',
            old_name='intel_datal_affecte_idx',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='intel_indic_ioc_typ_77138f_idx',
            old_name='intel_indic_ioc_typ_idx',
        ),
        migrations.RenameIndex(
            model_name='indicator',
            new_name='intel_indic_source_7bf65c_idx',
            old_name='intel_indic_source_idx',
        ),
        migrations.RenameIndex(
            model_name='threat',
            new_name='intel_threa_severit_152025_idx',
            old_name='intel_threa_severit_idx',
        ),
        migrations.RenameIndex(
            model_name='threat',
            new_name='intel_threa_source_f0274b_idx',
            old_name='intel_threa_source_idx',
        ),
    ]
