# Generated by Django 5.1.15 on 2026-07-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0012_feedsource_requires_tor'),
    ]

    operations = [
        migrations.AddField(
            model_name='threat',
            name='title_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='threat',
            name='title_vi',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='threat',
            name='title_vi_provider',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='threat',
            name='title_vi_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('rule', 'Rule'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='threat',
            name='title_vi_translated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
