# Generated by Django 5.1.15 on 2026-08-04 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel', '0017_threat_source_url_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreatFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "threat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="intel.threat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threat_favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="threatfavorite",
            index=models.Index(
                fields=["user", "created_at"],
                name="intel_fav_user_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="threatfavorite",
            index=models.Index(
                fields=["threat", "created_at"],
                name="intel_fav_threat_created_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="threatfavorite",
            constraint=models.UniqueConstraint(
                fields=("user", "threat"),
                name="uniq_threat_favorite_user_threat",
            ),
        ),
    ]
