# Generated by Django 5.1.15 on 2026-07-16 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(db_index=True, max_length=256)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('max_results', models.PositiveSmallIntegerField(default=250)),
                ('repository_count', models.PositiveIntegerField(default=0)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('alert_count', models.PositiveIntegerField(default=0)),
                ('critical_count', models.PositiveIntegerField(default=0)),
                ('non_text_count', models.PositiveIntegerField(default=0)),
                ('api_requests', models.PositiveIntegerField(default=0)),
                ('rate_limit_remaining', models.IntegerField(blank=True, null=True)),
                ('coverage_limited', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GitHubFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.CharField(db_index=True, max_length=512)),
                ('owner', models.CharField(blank=True, db_index=True, max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('extension', models.CharField(blank=True, db_index=True, max_length=32)),
                ('html_url', models.URLField(max_length=2048)),
                ('repository_url', models.URLField(blank=True, max_length=2048)),
                ('is_text_file', models.BooleanField(db_index=True, default=False)),
                ('keyword_matches', models.PositiveIntegerField(default=1)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('alert_types', models.JSONField(blank=True, default=list)),
                ('masked_evidence', models.TextField(blank=True)),
                ('secret_fingerprints', models.JSONField(blank=True, default=list)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.githubscan')),
            ],
            options={
                'ordering': ['-score', '-id'],
                'indexes': [models.Index(fields=['scan', '-score'], name='integration_scan_id_88bf74_idx'), models.Index(fields=['scan', 'severity'], name='integration_scan_id_a3f13c_idx')],
                'constraints': [models.UniqueConstraint(fields=('scan', 'repository', 'file_path'), name='uniq_github_scan_repository_file')],
            },
        ),
    ]
