# Generated by Django 5.1.15 on 2026-07-16 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_githubscan_githubfinding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubfinding',
            name='secret_fingerprints',
        ),
    ]
