# Generated by Django 5.1.15 on 2026-07-16 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_remove_githubfinding_secret_fingerprints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='githubscan',
            name='active_slot',
            field=models.BooleanField(editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='githubscan',
            constraint=models.UniqueConstraint(condition=models.Q(('active_slot', True)), fields=('active_slot',), name='uniq_active_github_scan'),
        ),
    ]
