# Generated by Django 5.1.15 on 2026-07-23 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_githubfinding_match_snippets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Last30DaysFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('host', models.CharField(blank=True, db_index=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('snippet', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('score', models.FloatField(db_index=True, default=0)),
                ('engagement_score', models.FloatField(default=0)),
                ('relevance', models.FloatField(default=0)),
                ('freshness', models.FloatField(default=0)),
                ('cluster_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('cluster_title', models.CharField(blank=True, max_length=512)),
                ('engagement', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-score', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Last30DaysResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(db_index=True, max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('depth', models.CharField(choices=[('quick', 'Quick'), ('default', 'Default'), ('deep', 'Deep')], default='quick', max_length=16)),
                ('lookback_days', models.PositiveSmallIntegerField(default=30)),
                ('max_results', models.PositiveSmallIntegerField(default=40)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('source_counts', models.JSONField(blank=True, default=dict)),
                ('item_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('clusters', models.JSONField(blank=True, default=list)),
                ('errors_by_source', models.JSONField(blank=True, default=dict)),
                ('brief_markdown', models.TextField(blank=True)),
                ('raw_report', models.JSONField(blank=True, default=dict)),
                ('stderr_tail', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('active_slot', models.BooleanField(editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Last 30 days research',
                'verbose_name_plural': 'Last 30 days researches',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.RenameIndex(
            model_name='githubfinding',
            new_name='integration_scan_id_a33802_idx',
            old_name='integratio_scan_id_repo_txt_idx',
        ),
        migrations.AddField(
            model_name='last30daysresearch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last30days_researches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='last30daysfinding',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='integrations.last30daysresearch'),
        ),
        migrations.AddConstraint(
            model_name='last30daysresearch',
            constraint=models.UniqueConstraint(condition=models.Q(('active_slot', True)), fields=('active_slot',), name='uniq_active_last30days_research'),
        ),
        migrations.AddIndex(
            model_name='last30daysfinding',
            index=models.Index(fields=['research', '-score'], name='integration_researc_b68e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='last30daysfinding',
            index=models.Index(fields=['research', 'source'], name='integration_researc_4ef3bf_idx'),
        ),
    ]
