# Generated by Django 5.1.15 on 2026-07-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_last30days_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='last30daysresearch',
            name='progress',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
