# Generated by Django 5.1.15 on 2026-07-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_last30days_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='last30daysresearch',
            name='progress_pct',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
